config/routes.rb
Vww::Application.routes.draw do
  resources :contacts, only: [:new, :create]
  resources :visitors, only: [:new, :create]
  root :to => 'visitors#new'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_no_table

  column :name, :string
  column :email, :string
  column :content, :string

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :content
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500

end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  has_no_table
  column :email, :string
  validates_presence_of :email
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

  def subscribe
    mailchimp = Gibbon.new
    result = mailchimp.list_subscribe({
      :id => ENV['MAILCHIMP_LIST_ID'],
      :email_address => self.email,
      :double_optin => false,
      :update_existing => true,
      :send_welcome => true
    })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  rescue Gibbon::MailChimpError => e
    Rails.logger.info("MailChimp subscribe failed for #{self.email}: " + e.message)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(secure_params)
    if @contact.valid?
      # send message here
      UserMailer.contact_email(@contact).deliver
      flash[:notice] = "Message sent from #{@contact.name}."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def secure_params
    params.require(:contact).permit(:name, :email, :content)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def new
    @visitor = Visitor.new
  end

  def create
    @visitor = Visitor.new(secure_params)
    if @visitor.valid?
      @visitor.subscribe
      flash[:notice] = "Signed up #{@visitor.email}."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def secure_params
    params.require(:visitor).permit(:email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>Contact<% end %>
<h3>Contact</h3>
  <%= simple_form_for @contact do |form| %>
  <%= form.error_notification %>
  <%= form.input :name, autofocus: true %>
  <%= form.input :email %>
  <%= form.input :content, as: :text, :input_html => { :class => "span6" } %>
  <%= form.button :submit, 'Submit', class: 'btn-primary' %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to 'Voice for Working Women', root_path, class: 'brand' %>
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'About', page_path('about') %></li>
  <li><%= link_to 'Contact', new_contact_path %></li>
  <li><%= link_to 'Source Code', "https://github.com/vysakh0/vww"%></li>
  <li><%= link_to 'Laws', "#"%></li>
  <li><%= link_to 'Groups', "#"%></li>
  <li><%= link_to 'Events', "#"%></li>
  <li><%= link_to 'Activists', "#"%></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Voice for Working Women" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Voice for working women" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About Voice for Women Forum</h3>
<p>This site is to address the problems Indian women face at working place. It tries to act as a bridge between woman(who face problem) with people
who can find solution to their problems.</p>
<p>We also curate a list of legislations, and powers that can be used to support the causes</p>

app/views/visitors/new.html.erb
<% content_for :title do %>Voice for working women<% end %>
<% content_for :description do %>Website of Foobar Kadigan<% end %>
<%= image_tag "woman.jpg" %>
<div style="text-align: center; margin-top: 20px">
  <div class="span4 offset2">
    <h2>Female Workers of India, Unite, Liberate!</h2>
  </div>
  <div class="span4">
    <div>
      <%= simple_form_for @visitor do |f| %>
        <%= f.error_notification %>
        <%= f.input :email, label: false, :placeholder => 'Your email address...' %>
        <br/>
        <%= f.submit "Sign up for the newsletter", :class => "btn btn-primary"%>
      <% end %>
      <b>Help line number:</b> 1324344
    </div>
  </div>
</div>